spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/libdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
    
management:
  endpoints:
    web:
      exposure:
        include: 
          - metrics
          - health
          - logfile

logging:
    pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n'
    file: 'logs/log.log'


